final List<String> countrys = [
  'Peru',
];
final List<String> departmentsPeru = [
  'Amazonas',
  'Áncash',
  'Apurímac',
  'Arequipa',
  'Ayacucho',
  'Cajamarca',
  'Callao',
  'Cusco',
  'Huancavelica',
  'Huánuco',
  'Ica',
  'Junín',
  'La Libertad',
  'Lambayeque',
  'Lima',
  'Loreto',
  'Madre de Dios',
  'Moquegua',
  'Pasco',
  'Piura',
  'Puno',
  'San Martín',
  'Tacna',
  'Tumbes',
  'Ucayali',
];
final List<String> provincialPeru = [
  'Chachapoyas',
  'Bagua',
  'Huaraz',
  'Aija',
  'Abancay',
  'Andahuaylas',
  'Arequipa',
  'Camaná',
  'Huamanga',
  'Cangallo',
  'Cajamarca',
  'Jaén',
  'Cusco',
  'Urubamba',
  'Huancavelica',
  'Acobamba',
  'Huánuco',
  'Leoncio Prado',
  'Ica',
  'Chincha',
];
final List<String> distritosLima = [
  'Ancón',
  'Ate',
  'Barranco',
  'Breña',
  'Carabayllo',
  'Cercado de Lima',
  'Chaclacayo',
  'Chorrillos',
  'Cieneguilla',
  'Comas',
  'El Agustino',
  'Independencia',
  'Jesús María',
  'La Molina',
  'La Victoria',
  'Lince',
  'Los Olivos',
  'Lurigancho-Chosica',
  'Lurín',
  'Magdalena del Mar',
  'Miraflores',
  'Pachacámac',
  'Pucusana',
  'Pueblo Libre',
  'Puente Piedra',
  'Punta Hermosa',
  'Punta Negra',
  'Rímac',
  'San Bartolo',
  'San Borja',
  'San Isidro',
  'San Juan de Lurigancho',
  'San Juan de Miraflores',
  'San Luis',
  'San Martín de Porres',
  'San Miguel',
  'Santa Anita',
  'Santa María del Mar',
  'Santa Rosa',
  'Santiago de Surco',
  'Surquillo',
  'Villa El Salvador',
  'Villa María del Triunfo',
];
final List<String> maritalStatus = [
  'Soltero',
  'Casado',
  'Divorciado',
];
final List<String> documentType = [
  'DNI',
  'Carné de extranjeria',
];
final List<String> workSituation = [
  'Empleado',
  'Independiente',
  'Desempleado',
];
final List<String> serviceTime = [
  'Menos de 6 meses',
  '6 meses a 1 año',
  '1 año a 2 años',
  '2 años a 3 años',
  '3 años a 4 años',
  '4 años a 5 años',
  '5 años a 6 años',
  'Mas de 6 años',
];
